[tool.poetry]
name = "st_snap"
version = "0.1.0"
description = ""
authors = ["Mitsuhisa Ota <mitsuhisa.ohta@brainpad.co.jp>"]

[tool.poetry.dependencies]
python = "^3.9"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
